# Generated by Django 3.0.3 on 2020-06-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvl5_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='mobile_no',
            field=models.IntegerField(blank=True, default=852),
            preserve_default=False,
        ),
    ]
