# Generated by Django 3.0.3 on 2020-06-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvl5_App', '0002_userprofileinfo_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
