# Generated by Django 3.0.3 on 2020-06-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvl5_App', '0003_auto_20200604_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='otp',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
